name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # ...
      - uses: philipparndt/vsce-action
        with:
          args: "package --allow-star-activation"
      - run: echo "name=$(ls | grep vsix | sort | tail -n 1)" >> $GITHUB_OUTPUT
        id: identify-package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.identify-package.outputs.name}}
