name: Build and Publish Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # ...
      - name: Setup Node.js
        uses: node:16-slim

      - name: Install dependencies
        run: npm install && npm i -g @vscode/vsce

      - name: Build extension
        run: npm run build

      - name: Package extension
        run: vsce package

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SCERET_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload .vsix file
        uses: actions/upload-artifact@v2
        with:
          name: vsix
          path: "*.vsix"

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ${{steps.identify-package.outputs.name}}
